// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_calc_cov
Rcpp::NumericMatrix rcpp_calc_cov(arma::mat tmat);
RcppExport SEXP _distdecay_rcpp_calc_cov(SEXP tmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type tmat(tmatSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_calc_cov(tmat));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_calc_mi
Rcpp::NumericMatrix rcpp_calc_mi(arma::mat tmat);
RcppExport SEXP _distdecay_rcpp_calc_mi(SEXP tmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type tmat(tmatSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_calc_mi(tmat));
    return rcpp_result_gen;
END_RCPP
}
