# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_calc_cov
#'
#' Calculate pairwise covariance matrix between input trip matrix. Upper
#' diagonal is between all trips **from** i and j; lower diagonal holds
#' covariances between all trips **to** j and i. This can't be done easily in
#' Armadillo because the zero entries need to be removed, and arma's inbuilt
#' cov function doesn't ignore zeros, and any nan or inf values generate
#' resultant NA covariances for the whole row.
#' 
#' @export
rcpp_calc_cov <- function(tmat) {
    .Call(`_distdecay_rcpp_calc_cov`, tmat)
}

#' test
#' @noRd
test <- function() {
    .Call(`_distdecay_test`)
}

